import {Digit, DigitChar} from "./digit";

/**
 * @constant Table for fast digit comparison.
 */
type DigitMinusSource = [
    [
        Digit.Zero,
        Digit.One,
        Digit.Two,
        Digit.Three,
        Digit.Four,
        Digit.Five,
        Digit.Four,
        Digit.Three,
        Digit.Two,
        Digit.One
    ],
    [
        Digit.One,
        Digit.Zero,
        Digit.One,
        Digit.Two,
        Digit.Three,
        Digit.Four,
        Digit.Five,
        Digit.Four,
        Digit.Three,
        Digit.Two
    ],
    [
        Digit.Two,
        Digit.One,
        Digit.Zero,
        Digit.One,
        Digit.Two,
        Digit.Three,
        Digit.Four,
        Digit.Five,
        Digit.Four,
        Digit.Three
    ],
    [
        Digit.Three,
        Digit.Two,
        Digit.One,
        Digit.Zero,
        Digit.One,
        Digit.Two,
        Digit.Three,
        Digit.Four,
        Digit.Five,
        Digit.Four
    ],
    [
        Digit.Four,
        Digit.Three,
        Digit.Two,
        Digit.One,
        Digit.Zero,
        Digit.One,
        Digit.Two,
        Digit.Three,
        Digit.Four,
        Digit.Five
    ],
    [
        Digit.Five,
        Digit.Four,
        Digit.Three,
        Digit.Two,
        Digit.One,
        Digit.Zero,
        Digit.One,
        Digit.Two,
        Digit.Three,
        Digit.Four
    ],
    [
        Digit.Four,
        Digit.Five,
        Digit.Four,
        Digit.Three,
        Digit.Two,
        Digit.One,
        Digit.Zero,
        Digit.One,
        Digit.Two,
        Digit.Three
    ],
    [
        Digit.Three,
        Digit.Four,
        Digit.Five,
        Digit.Four,
        Digit.Three,
        Digit.Two,
        Digit.One,
        Digit.Zero,
        Digit.One,
        Digit.Two
    ],
    [
        Digit.Two,
        Digit.Three,
        Digit.Four,
        Digit.Five,
        Digit.Four,
        Digit.Three,
        Digit.Two,
        Digit.One,
        Digit.Zero,
        Digit.One
    ],
    [
        Digit.One,
        Digit.Two,
        Digit.Three,
        Digit.Four,
        Digit.Five,
        Digit.Four,
        Digit.Three,
        Digit.Two,
        Digit.One,
        Digit.Zero
    ]
];

export type DigitDistance<
    T extends Digit | DigitChar,
    U extends Digit | DigitChar
> = DigitMinusSource[T][U];
